# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [ ]:
# your code here
import pandas as pd 
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [25]:
# 1: Read the dataset
df = pd.read_csv('tic-tac-toe.csv').copy()

# 2: Inspect the dataset
print(df.head())
print(df.info())

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   TL      958 non-null    object
 1   TM      958 non-null    object
 2   TR      958 non-null    object
 3   ML      958 non-null    object
 4   MM      958 non-null    object
 5   MR      958 non-null    object
 6   BL      958 non-null    object
 7   BM      958 non-null    object
 8   BR      958 non-null    object
 9   class   958 non-null    bool  
dtypes: bool(1), object(9)
memory usage: 68.4+ KB
None


In [26]:
# 3: Convert categorical values to numeric
mapping = {'x': 1, 'o': -1, 'b': 0}
df.iloc[:, :-1] = df.iloc[:, :-1].applymap(lambda x: mapping[x])
df['class'] = df['class'].astype(int)  # Convert class to numeric (True -> 1, False -> 0)


In [46]:
print(df.head())
print(df.info())

  TL TM TR ML  MM  MR  BL  BM  BR  class
0  1  1  1  1  -1  -1   1  -1  -1      1
1  1  1  1  1  -1  -1  -1   1  -1      1
2  1  1  1  1  -1  -1  -1  -1   1      1
3  1  1  1  1  -1  -1  -1   0   0      1
4  1  1  1  1  -1  -1   0  -1   0      1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   TL      958 non-null    object
 1   TM      958 non-null    object
 2   TR      958 non-null    object
 3   ML      958 non-null    object
 4   MM      958 non-null    object
 5   MR      958 non-null    object
 6   BL      958 non-null    object
 7   BM      958 non-null    object
 8   BR      958 non-null    object
 9   class   958 non-null    int32 
dtypes: int32(1), object(9)
memory usage: 71.2+ KB
None


In [27]:
# 4: Separate inputs and output
X = df.iloc[:, :-1]  # First 9 columns as input
y = df['class']      # Last column as output


In [28]:
# 5: Normalize the input data
scaler = MinMaxScaler()
X_normalized = scaler.fit_transform(X)

# Convert back to DataFrame if needed
X_normalized = pd.DataFrame(X_normalized, columns=X.columns)

print(X_normalized.head())

    TL   TM   TR   ML   MM   MR   BL   BM   BR
0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0
1  1.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0
2  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0
3  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.5  0.5
4  1.0  1.0  1.0  1.0  0.0  0.0  0.5  0.0  0.5


## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [34]:
# your code here
# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_normalized, y, test_size=0.2, random_state=42)


In [35]:

# Create Sequential and Build the neural network model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation='relu', input_shape=(9,)),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


In [36]:
# Train the model
model.fit(X_train, y_train, epochs=50, validation_data=(X_test, y_test), verbose=1)

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Accuracy: {accuracy:.4f}')

Epoch 1/50
24/24 [==============================] - 2s 13ms/step - loss: 0.6349 - accuracy: 0.6632 - val_loss: 0.6309 - val_accuracy: 0.6615
Epoch 2/50
24/24 [==============================] - 0s 5ms/step - loss: 0.6161 - accuracy: 0.6606 - val_loss: 0.6188 - val_accuracy: 0.6562
Epoch 3/50
24/24 [==============================] - 0s 5ms/step - loss: 0.6032 - accuracy: 0.6762 - val_loss: 0.6074 - val_accuracy: 0.6823
Epoch 4/50
24/24 [==============================] - 0s 4ms/step - loss: 0.5895 - accuracy: 0.7076 - val_loss: 0.5947 - val_accuracy: 0.6927
Epoch 5/50
24/24 [==============================] - 0s 5ms/step - loss: 0.5751 - accuracy: 0.7219 - val_loss: 0.5801 - val_accuracy: 0.6979
Epoch 6/50
24/24 [==============================] - 0s 4ms/step - loss: 0.5606 - accuracy: 0.7324 - val_loss: 0.5643 - val_accuracy: 0.7135
Epoch 7/50
24/24 [==============================] - 0s 4ms/step - loss: 0.5456 - accuracy: 0.7441 - val_loss: 0.5488 - val_accuracy: 0.7292
Epoch 8/50
24/24 [=

In [37]:
# Save the model
model.save('tic-tac-toe.model')

INFO:tensorflow:Assets written to: tic-tac-toe.model\assets


INFO:tensorflow:Assets written to: tic-tac-toe.model\assets


## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [38]:
# your code here
# Load the saved model
loaded_model = tf.keras.models.load_model('tic-tac-toe.model')

# Make predictions on random test samples
random_sample = np.random.choice(len(X_test), 5, replace=False)
X_sample = X_test.iloc[random_sample]
y_actual = y_test.iloc[random_sample]

pred = loaded_model.predict(X_sample)
pred_classes = np.argmax(pred, axis=1)

# Print predictions and actual values to check if they are correct
for i in range(len(random_sample)):
    print(f'Board state {i+1}:')
    print(X_sample.iloc[i].values.reshape(3, 3))
    print(f'Actual: {y_actual.iloc[i]}, Predicted: {pred_classes[i]}')
    print('-' * 30)


1/1 [==============================] - 0s 107ms/step
Board state 1:
[[1. 1. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
Actual: 1, Predicted: 1
------------------------------
Board state 2:
[[0.5 0.5 1. ]
 [0.5 1.  0. ]
 [1.  0.  0.5]]
Actual: 1, Predicted: 1
------------------------------
Board state 3:
[[0.5 1.  1. ]
 [0.  0.  0. ]
 [1.  0.5 0.5]]
Actual: 0, Predicted: 0
------------------------------
Board state 4:
[[1.  0.5 0. ]
 [1.  1.  0. ]
 [0.5 0.5 0. ]]
Actual: 0, Predicted: 1
------------------------------
Board state 5:
[[0.5 1.  0. ]
 [0.5 0.  0.5]
 [0.  1.  1. ]]
Actual: 0, Predicted: 0
------------------------------


## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [43]:
# your code here
# Build the improved neural network model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(32, activation='relu', input_shape=(9,)),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')
])

# Compile the model with a custom learning rate
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model with increased epochs
model.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test), verbose=1)



Epoch 1/100
24/24 [==============================] - 2s 12ms/step - loss: 0.6331 - accuracy: 0.6632 - val_loss: 0.6142 - val_accuracy: 0.6510
Epoch 2/100
24/24 [==============================] - 0s 4ms/step - loss: 0.6045 - accuracy: 0.6540 - val_loss: 0.5911 - val_accuracy: 0.6510
Epoch 3/100
24/24 [==============================] - 0s 4ms/step - loss: 0.5801 - accuracy: 0.6971 - val_loss: 0.5626 - val_accuracy: 0.7083
Epoch 4/100
24/24 [==============================] - 0s 4ms/step - loss: 0.5554 - accuracy: 0.7232 - val_loss: 0.5409 - val_accuracy: 0.7188
Epoch 5/100
24/24 [==============================] - 0s 4ms/step - loss: 0.5373 - accuracy: 0.7493 - val_loss: 0.5275 - val_accuracy: 0.7344
Epoch 6/100
24/24 [==============================] - 0s 4ms/step - loss: 0.5195 - accuracy: 0.7624 - val_loss: 0.5081 - val_accuracy: 0.7500
Epoch 7/100
24/24 [==============================] - 0s 4ms/step - loss: 0.5007 - accuracy: 0.7755 - val_loss: 0.4983 - val_accuracy: 0.7552
Epoch 8/100


In [44]:
# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Accuracy: {accuracy:.4f}')

6/6 [==============================] - 0s 3ms/step - loss: 0.0446 - accuracy: 0.9844
Test Accuracy: 0.9844


In [47]:
model.save('tic-tac-toe.model')
loaded_model = tf.keras.models.load_model('tic-tac-toe.model')

INFO:tensorflow:Assets written to: tic-tac-toe.model\assets


INFO:tensorflow:Assets written to: tic-tac-toe.model\assets


**Which approach(es) did you find helpful to improve your model performance?**

The following approaches helped improve the model's performance:

1- Adding More Layers: Increasing the number of hidden layers from 2 to 3 helped capture more complex patterns in the Tic Tac Toe board states.

2- Increasing Neurons Per Layer:
Expanding from 16 neurons to 32 in the first two layers improved learning capacity.

3- Adjusting the Learning Rate:
Using tf.keras.optimizers.Adam(learning_rate=0.001) instead of the default helped balance convergence speed and stability.

4- Training for More Epochs:
Increasing the epochs to 100 allowed the model to learn better without overfitting.

In [48]:
# your answer here
''' 
Adding more layers , increase Neurons , use learning_rate=0.001 , incerease the epochs 
'''

' \nAdding more layers , increase Neurons , use learning_rate=0.001 , incerease the epochs \n'